name: FastAPI CI

on: 
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_TOKEN}}
      
      - name: Build Docker Image
        uses: docker/build-push-action@v3.2.0
        with: 
          context: ./
          file: ./Dockerfile
          push: false
          tags: |
            elizeu333/fastapi_alunos:${{ github.run_number }}
            elizeu333/fastapi_alunos:latest

  scan:
    runs-on: ubuntu-latest
    needs: build  
    steps:
      - name: Checkout Git
        uses: actions/checkout@v4

      - name: Scan Docker Image with Trivy
        uses: aquasecurity/trivy-action@v0.11.0
        with:
          image-ref: elizeu333/fastapi_alunos:${{ github.run_number }}
          severity: CRITICAL,HIGH  
          exit-code: 1              # Define o código de saída 1 se vulnerabilidades críticas ou altas forem encontradas
