name: FastAPI CI

on: 
  push:
    branches:
      - dev

    
jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout git
        uses: actions/checkout@v4
        
      - name: build image
        run: docker build . -t elizeu333/project_fastapi:${{ github.run_number }}
        
      - name: login 
        run: docker login -u "${{ secrets.DOCKER_USER }}" -p "${{ secrets.DOCKER_TOKEN }}"

      - name: push dockerhub
        run: docker push elizeu333/project_fastapi:${{ github.run_number }}
