name: FastAPI CI

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Instalar Docker
      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install docker.io -y

      # Step 3: Construir e rodar a imagem Docker usando Alpine
      - name: Build and Run Docker Container
        run: |
          docker build -t my-fastapi-app .
          docker run -d --name fastapi-container -p 8080:8080 my-fastapi-app

      # Step 4: Esperar PostgreSQL estar disponível
      - name: Wait for PostgreSQL
        run: |
          until docker exec fastapi-container pg_isready -U admin; do
            echo "Waiting for PostgreSQL...";
            sleep 5;
          done

      # Step 5: Testar se o serviço web está rodando
      - name: Check if web is running
        run: curl http://localhost:8080/ -o /dev/null -s -w "%{http_code}\n" | grep 200 || exit 1

      # Step 6: Parar o container
      - name: Stop the Docker container
        run: docker stop fastapi-container

      # Step 7: Remover o container
      - name: Remove the Docker container
        run: docker rm fastapi-container
