name: FastAPI CI

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_TOKEN}}
      
      - name: Build Docker Image
        uses: docker/build-push-action@v3.2.0
        with: 
          context: ./
          file: ./Dockerfile
          push: false
          tags: |
            elizeu333/fastapi_alunos:${{ github.run_number }}
            elizeu333/fastapi_alunos:latest

      - name: Save Docker Image as Artifact
        run: docker save elizeu333/fastapi_alunos:${{ github.run_number }} elizeu333/fastapi_alunos:latest -o image.tar
          
      - name: Upload Docker Image Artifact
        uses: actions/upload-artifact@v3
        with:
           name: docker-image
           path: image.tar
          
  scan-trivy:
    runs-on: ubuntu-latest
    needs: build  
    steps:
      - name: Download Docker Image Artifact
        uses: actions/download-artifact@v3
        with:
          name: docker-image
          
      - name: Load Docker Image
        run: docker load -i image.tar
        
      - name: Scan Docker Image with Trivy
        uses: aquasecurity/trivy-action@0.25.0
        with:
          image-ref: elizeu333/fastapi_alunos:${{ github.run_number }}
          severity: CRITICAL,HIGH  
          exit-code: 1
          
  push:
    runs-on: ubuntu-latest
    needs: scan-trivy
    steps:
      - name: Checkout Git
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_TOKEN}}
      
      - name: Download Docker Image Artifact
        uses: actions/download-artifact@v3
        with:
          name: docker-image
      
      - name: Load Docker Image
        run: docker load -i image.tar

      - name: Push Docker Image to Docker Hub
        run: |
          docker push elizeu333/fastapi_alunos:${{ github.run_number }}
          docker push elizeu333/fastapi_alunos:latest
