name: FastAPI CI

on: 
  push:
    branches:
      - dev

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git
        uses: actions/checkout@v4
        
      - name: Build Docker Image
        run: docker build . -t elizeu333/fastapi_alunos:${{ github.run_number }}
        
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN }}

      - name: Push Docker Image to Docker Hub
        run: docker push elizeu333/fastapi_alunos:${{ github.run_number }}
