name: FastAPI CI

on: 
  push:
    branches:
      - dev

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git
        uses: actions/checkout@v4
        
      - name: Build Docker Image
        run: docker build . -t elizeu333/project_fastapi:${{ github.run_number }}
        
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Push Docker Image to Docker Hub
        run: docker push elizeu333/project_fastapi:${{ github.run_number }}
